include: ['_pages']

# Site settings
title: Dave Berning | Web Developer
firstName: Dave
lastName: Berning
devSubCap: A Web Developer from
location: Cincinnati, OH
email: daveberning@icloud.com
description: Dave Berning is a web developer and designer from Cincinnat, OH.
avatar: images/dave.jpg

# URLs
baseurl: "/"
url: "http://localhost:4000" # the base hostname & protocol for your site
projectURL: "http://localhost:4000/project/"
imagesURL: "http://localhost:4000/images/"

# Social Media Accounts
facebook: https://www.facebook.com/dave.berning.iii
twitter: https://twitter.com/daveberning
linkedin: https://www.linkedin.com/in/davidberning
instagram: https://www.instagram.com/daveberning/
github: https://github.com/daveberning
codepen: https://codepen.io/daveberning

# Collections
collections:
  testimonials:
  content:
  projects:
      output: true
      permalink: '/:categories/:title'

# Build settings
markdown: kramdown
permalink: /:title
sass_dir: public/_scss
sass:
  style: compressed
