include: ['_pages']

# Site settings
title: Dave Berning | Web Developer | Cincinnati, OH
firstName: Dave
lastName: Berning
devSubCap: A Web Developer from
location: Cincinnati, OH
email: daveberning@icloud.com
description: Dave Berning is a web developer and designer from Cincinnat, OH.
avatar: images/dave.jpg

# URLs
baseurl: "/"
url: "https://daveberning.github.io/daveberning.io" # the base hostname & protocol for your site
projectURL: "https://daveberning.github.io/daveberning.io/project/"
imagesURL: "https://daveberning.github.io/daveberning.io/images/"

# Social Media Accounts
facebook: https://www.facebook.com/dave.berning.iii
twitter: https://twitter.com/daveberning
linkedin: https://www.linkedin.com/in/davidberning
instagram: https://www.instagram.com/daveberning/
github: https://github.com/daveberning
codepen: https://codepen.io/daveberning

# Collections
collections:
  testimonials:
  content:
  projects:
      output: true
      permalink: '/:categories/:title'

#Gems
gems: [jekyll-paginate, jekyll-gist, jekyll-seo-tag, octopress-minify-html]
paginate: 5
paginate_path: /blog/:num/

# Build settings
markdown: kramdown
permalink: /:title
sass_dir: public/_scss
sass:
  style: compressed
