# Site settings
title: Dave Berning | Web Developer
firstName: Dave
lastName: Berning
devSubCap: A Web Developer from
location: Cincinnati, OH
email: daveberning@icloud.com
description: Dave Berning is a web developer and designer from Cincinnat, OH.
baseurl: "/"
url: "http://localhost:4000/" # the base hostname & protocol for your site
images: "{{site.url}}images/"

collections:
  testimonials:
  projects:
      output: true
      permalink: '/:categories/:title'

# Build settings
markdown: kramdown
permalink: /:title
