---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: all
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: _projects
  label: Projects
  create: all
  match: "**/*"
- type: directory
  path: _content
  label: Content
  create: all
  match: "**/*"
- type: directory
  path: _testimonials
  label: Testimonials
  create: all
  match: "**/*"
upload_dir: images
public_path: images
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
